import IconSection from '@/components/Home/IconSection/IconSection';
import Intro from '@/components/Home/Intro/Intro';
import Landing from '@/components/Home/Landing/Landing';
import Project from '@/components/Home/Project/Project';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Conservation Resources Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Landing />
        <IconSection />
        <Intro />
        <Project />
      </main>
    </>
  );
}
